
server:
  port: 30001

config:

  allow-cors-origins:
    - http://localhost:3000

    file-path: /Users/Documents/file/format.json

  # create log header or  required information.
  outbound-log-info:
    leef-info:
      leef-version: 2.0
      vendor: Leo
      product-name: log-choco
      product-version: 1.0.0
      delimiter: ','
      include-syslog-header: true

    cef-info:
      vendor: Leo
      product-name: log-choco
      product-version: 1.0.0

      default-severity: VERY-LOW
      default-event-name: default event name
      defualt-event-name-mapper:
        accessAllow: allow access
        accessDeny: deny Access
        aceessWarn: warn Access

      include-syslog-header: true


  #set server information which receives logs from.
  receive-server:
    - port: 20001
      protocol: TCP

    - port: 20002
      protocol: UDP

  #set servers information which send logs to
  target-server:
    - ip: 192.168.219.102
      port: 30001
      protocol: TCP





