
server:
  port: 30001

config:
  file-path: /Users/Heesu/Documents/file/format.json

  # create log header or  required information.
  outbound-log-info:
    leef-version: 2.0
    vendor: Leo
    product-name: log-choco
    product-version: 2.0
    delimiter: ','
    include-syslog-header: true




  #set server information which receives logs from.
  receive-server:
      - port: 20001
        protocol: TCP

      - port: 20002
        protocol: UDP

